[project]
name = "llm-chain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.4.4",
    "langchain[openai]>=0.3.26",
]
